ifndef USERSPACE_DIR
$(error USERSPACE_DIR must be defined before including runtime_config.mk)
endif

USERSPACE_RUNTIME ?= musl

USERSPACE_RUNTIME_DIR := $(USERSPACE_DIR)/runtime
USERSPACE_MIGRATION_SYSROOT := $(USERSPACE_RUNTIME_DIR)/sysroot
USERSPACE_LIBC_DIR := $(USERSPACE_DIR)/libc
USERSPACE_RUNTIME_CRT0 := $(USERSPACE_LIBC_DIR)/crt0.o
USERSPACE_RUNTIME_GLUE_OBJ := $(USERSPACE_LIBC_DIR)/runtime_glue.o
USERSPACE_C_MAIN_BRIDGE_OBJ := $(USERSPACE_LIBC_DIR)/c_main_bridge.o
USERSPACE_CXX_MAIN_BRIDGE_OBJ := $(USERSPACE_LIBC_DIR)/cxx_main_bridge.o
USERSPACE_MUSL_VENDOR_DIR := $(USERSPACE_RUNTIME_DIR)/vendor/musl
USERSPACE_MUSL_PATCH_DIR := $(USERSPACE_RUNTIME_DIR)/patches/musl
USERSPACE_RUNTIME_SYSTEM_LIBS := -lc -lm -lgcc

ifeq ($(USERSPACE_RUNTIME),musl)
USERSPACE_ACTIVE_SYSROOT := $(USERSPACE_MIGRATION_SYSROOT)
USERSPACE_HEADER_SYSROOT := $(USERSPACE_MIGRATION_SYSROOT)
USERSPACE_LINK_SYSROOT := $(USERSPACE_MIGRATION_SYSROOT)
USERSPACE_GLUE_SYSROOT := $(USERSPACE_MIGRATION_SYSROOT)
USERSPACE_RUNTIME_DISPLAY := musl-libcxx
USERSPACE_RUNTIME_SETUP_HINT := bash ../../scripts/setup_userspace_runtime.sh
USERSPACE_RUNTIME_CHECK_FILE := $(USERSPACE_HEADER_SYSROOT)/include/stdio.h
USERSPACE_RUNTIME_LIBC_CHECK_FILE := $(USERSPACE_LINK_SYSROOT)/lib/libc.a
else ifeq ($(USERSPACE_RUNTIME),runtime)
USERSPACE_ACTIVE_SYSROOT := $(USERSPACE_MIGRATION_SYSROOT)
USERSPACE_HEADER_SYSROOT := $(USERSPACE_MIGRATION_SYSROOT)
USERSPACE_LINK_SYSROOT := $(USERSPACE_MIGRATION_SYSROOT)
USERSPACE_GLUE_SYSROOT := $(USERSPACE_MIGRATION_SYSROOT)
USERSPACE_RUNTIME_DISPLAY := musl-libcxx
USERSPACE_RUNTIME_SETUP_HINT := bash ../../scripts/setup_userspace_runtime.sh
USERSPACE_RUNTIME_CHECK_FILE := $(USERSPACE_HEADER_SYSROOT)/include/stdio.h
USERSPACE_RUNTIME_LIBC_CHECK_FILE := $(USERSPACE_LINK_SYSROOT)/lib/libc.a
else
$(error Unsupported USERSPACE_RUNTIME='$(USERSPACE_RUNTIME)' (expected musl))
endif

USERSPACE_RUNTIME_LIBC_CHECK_FILE ?= $(USERSPACE_LINK_SYSROOT)/lib/libc.a
