#ifndef VK_QUAKE_SDL_HINTS_H
#define VK_QUAKE_SDL_HINTS_H
#include "SDL.h"
#define SDL_HINT_MOUSE_RELATIVE_SYSTEM_SCALE "SDL_MOUSE_RELATIVE_SYSTEM_SCALE"
#define SDL_HINT_NO_SIGNAL_HANDLERS          "SDL_NO_SIGNAL_HANDLERS"
#endif
